create database DoAn
use DoAn

-- T?o database

-- 1. SINHVIEN
CREATE TABLE SINHVIEN (
    MSSV CHAR(6) PRIMARY KEY,
    TENSV VARCHAR(30),
    SODT VARCHAR(9),
    LOP CHAR(6),
    DIACHI VARCHAR(50)
);

-- 2. DETAI
CREATE TABLE DETAI (
    MSDT CHAR(6) PRIMARY KEY,
    TENDT VARCHAR(30)
);

-- 3. SV_DETAI
CREATE TABLE SV_DETAI (
    MSSV CHAR(6),
    MSDT CHAR(6),
    PRIMARY KEY (MSSV, MSDT),
    FOREIGN KEY (MSSV) REFERENCES SINHVIEN(MSSV),
    FOREIGN KEY (MSDT) REFERENCES DETAI(MSDT)
);

-- 4. HOCHAM
CREATE TABLE HOCHAM (
    MSHH SMALLINT PRIMARY KEY,
    TENHH VARCHAR(20)
);

-- 5. HOCVI
CREATE TABLE HOCVI (
    MSHV SMALLINT PRIMARY KEY,
    TENHV VARCHAR(10)
);

-- 6. CHUYENNGANH
CREATE TABLE CHUYENNGANH (
    MSCN SMALLINT PRIMARY KEY,
    TENCN VARCHAR(30)
);

-- 7. GIAOVIEN
CREATE TABLE GIAOVIEN (
    MSGV SMALLINT PRIMARY KEY,
    TENGV VARCHAR(30),
    DIACHI VARCHAR(50),
    SODT VARCHAR(9),
    MSHHAM SMALLINT NULL,
    NAMHH SMALLDATETIME,
    FOREIGN KEY (MSHHAM) REFERENCES HOCHAM(MSHH)
);

-- 8. GV_HV_CN
CREATE TABLE GV_HV_CN (
    MSGV SMALLINT,
    MSHV SMALLINT,
    MSCN SMALLINT,
    NAM SMALLDATETIME,
    PRIMARY KEY (MSGV, MSHV, MSCN),
    FOREIGN KEY (MSGV) REFERENCES GIAOVIEN(MSGV),
    FOREIGN KEY (MSHV) REFERENCES HOCVI(MSHV),
    FOREIGN KEY (MSCN) REFERENCES CHUYENNGANH(MSCN)
);

-- 9. GV_HDDT
CREATE TABLE GV_HDDT (
    MSGV SMALLINT,
    MSDT CHAR(6),
    DIEM FLOAT,
    PRIMARY KEY (MSGV, MSDT),
    FOREIGN KEY (MSGV) REFERENCES GIAOVIEN(MSGV),
    FOREIGN KEY (MSDT) REFERENCES DETAI(MSDT)
);

-- 10. GV_PBDT
CREATE TABLE GV_PBDT (
    MSGV SMALLINT,
    MSDT CHAR(6),
    DIEM FLOAT,
    PRIMARY KEY (MSGV, MSDT),
    FOREIGN KEY (MSGV) REFERENCES GIAOVIEN(MSGV),
    FOREIGN KEY (MSDT) REFERENCES DETAI(MSDT)
);

-- 11. GV_UVDT
CREATE TABLE GV_UVDT (
    MSGV SMALLINT,
    MSDT CHAR(6),
    DIEM FLOAT,
    PRIMARY KEY (MSGV, MSDT),
    FOREIGN KEY (MSGV) REFERENCES GIAOVIEN(MSGV),
    FOREIGN KEY (MSDT) REFERENCES DETAI(MSDT)
);

-- 12. HOIDONG
CREATE TABLE HOIDONG (
    MSHD SMALLINT PRIMARY KEY,
    PHONG SMALLINT,
    TGBD SMALLDATETIME,
    NGAYHD SMALLDATETIME,
    TINHTRANG VARCHAR(30),
    MSGVCTHD SMALLINT,
    FOREIGN KEY (MSGVCTHD) REFERENCES GIAOVIEN(MSGV)
);

-- 13. HOIDONG_GV
CREATE TABLE HOIDONG_GV (
    MSHD SMALLINT,
    MSGV SMALLINT,
    PRIMARY KEY (MSHD, MSGV),
    FOREIGN KEY (MSHD) REFERENCES HOIDONG(MSHD),
    FOREIGN KEY (MSGV) REFERENCES GIAOVIEN(MSGV)
);

-- 14. HOIDONG_DT
CREATE TABLE HOIDONG_DT (
    MSHD SMALLINT,
    MSDT CHAR(6),
    QUYETDINH CHAR(10),
    PRIMARY KEY (MSHD, MSDT),
    FOREIGN KEY (MSHD) REFERENCES HOIDONG(MSHD),
    FOREIGN KEY (MSDT) REFERENCES DETAI(MSDT)
);
